### ISSUE TITLE
Make proprietary dependencies optional

### ISSUE THREAD

**Issue by relan** [spacecowboy/NotePad#269]
Currently NoNonsense Notes depends on proprietary libraries/services from Google. While most Android devices have Google Apps preinstalled, there are cases when they are missing:
1. Some people do not use them because they violate their privacy and freedom.
2. All (?) devices in the Chinese market do not have Google Apps preinstalled.
3. Almost all custom ROMs (including CyanogenMod—the most popular of them) do not include them because this violates Google's terms of use.
4. There are devices like Jolla, Nokia X, Kindle Fire Phone, Blackberry, etc. that can run Android apps but do not have Google Apps on them.

It would be great if NoNonsense Notes had a compile-time option to disable proprietary dependencies. It's OK to loose some functionality (GTasks synchronization, location-aware reminders, maybe something else?).

I've seen comment about possible Google-less fork in #254 but current state of this idea is unclear.

P.S. Awesome app that works and looks extremely well, would love to see it in the F-Droid repo.

**Comment by licaon-kter** [comment]
5.7.0 app-free-release.apk fails to install on a GoogleServices free device where 5.5.5 from F-Droid is installed.

Or am I missing the point?

**Comment by spacecowboy** [comment]
Hmm. It should work. I can't say "it works on my device", since I obviously have googleservices on my phone. But it does work there though.

Any chance you could supply a crash log through adb? If not that's OK. 5.7.0 does not change anything for the free version. It only updates the dropbox things in the playBeta-version.

**Comment by spacecowboy** [comment]
@licaon-kter I just realized your problem. F-Droid signs the apks using their own key. You'll have to uninstall that before you can install the apk from github.

**Comment by licaon-kter** [comment]
Ok, it worked, 10q.

Although now, by uninstalling, I'm hit by these issues in order: https://github.com/spacecowboy/NotePad/issues/305 , https://github.com/spacecowboy/NotePad/issues/310 and https://github.com/spacecowboy/NotePad/issues/306 :(

**Comment by spacecowboy** [comment]
Living on the edge can be like that sometimes
