### ISSUE TITLE
Tasks due within 1 week should not be "later" (suggestion)

### ISSUE THREAD

**Issue by quite** [spacecowboy/NotePad#289]
I propose that tasks which are due within 24_7 hours be group in the respective Today, Tomorrow, Friday, Saturday, etc groups. And also that tasks due >24_7 hours from now be grouped in Later.

The thing is that currently, the threshold for Later is shorter than that (not sure how short), so the task I have on Monday (today is Wednesday) is group in the Later group. But my feeling is that it is closer in time than "Later" -- it's in only 5 days!

Does this make sense? Or would it make sense to have some other value than 24*7? Or are you happy with the current value (whatever that is)?

**Comment by spacecowboy** [comment]
The current value is 5 days into the future. This is of course completely arbitrary but my reasoning was that on Monday morning, one should see the entire work week.

If you look at the list any other day in the week however, the last day before "Later" will always feel arbitrary.

This is of course unless one is more clever, and has a variable end such as "next sunday" or something. This was not convenient to do at the time, but is more convenient with the current code base available. So I'll keep this issue open just for that purpose.

**Comment by CampelloManuel** [comment]
added "next month" and "next year" in 7.1.2, so this is done.
