### ISSUE TITLE
Separate title field or personalised title text size

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#296]
Would that be possible? I would like to be able to use a title or not.

Right now even for notes the first entry ( that ends up as a forced title) will be a slightly bigger font size.

Or better yet, allow "title size as normal text" option or something.

Thanks

**Comment by spacecowboy** [comment]
Considering all the other options regarding title style, yes I'll add that option

**Comment by licaon-kter** [comment]
Thank you.

**Comment by licaon-kter** [comment]
Ok so, now I see that the Appearance option has it but the List option does not, yielding a same size title ( first row ahem ) when editing a list/task *but* the list view still has the first row with a slightly bigger font size.
