### ISSUE TITLE
Checkboxes in lists

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#297]
While a per note/task checkbox is nice, inside a note/task a per item checkbox would be helpful as notes/task usually have many subitems.

Thanks

**Comment by spacecowboy** [comment]
I agree it would be suitable, but unfortunately it's not possible with the current structure and legacy dependency on google tasks. It would be possible with the file-based backend (SD-card/Dropbox) but there's no way to differentiate from GTask support atm.

**Comment by licaon-kter** [comment]
Oh, ok.
