### ISSUE TITLE
Default reminder date

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#298]
As of right now it's on "*next day* 09:00", so if I want something for later today I will change the day and **bing** the phone will have a instant notification while I'm in the middle of setting up the reminder ( since 09:00 today has passed ).

Two ideas:

* default reminder changed to *current_time* + 1 hour
* set reminder *after* choosing an hour or after exiting the note to go back to the list

Thanks

**Comment by spacecowboy** [comment]
I like the first idea. It's the minimal change to app.

**Comment by licaon-kter** [comment]
Thank you.
