### ISSUE TITLE
Sync option: Task Warrior

### ISSUE THREAD

**Issue by spacecowboy** [spacecowboy/NotePad#308]
Command line interface, exports/imports JSON files

http://taskwarrior.org/docs/design/task.html

**Comment by cwmke** [comment]
This would be a wonderful addition.  Mirakel is currently the ownly Android client for TW and sync is broken on the latest version.

**Comment by spacecowboy** [comment]
@cwmke I have planned to add support once 6.1 it done (currently working on 6.0). Will revamp the entire sync part of the app to be compatible with multiple backends in a proper way.
