### ISSUE TITLE
SD Card sync ( org mode ) note/tasks missing manual order properties

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#310]
Basically items are stored in created ( afaics ) order, making notes/tasks sorted wrong on import.

**Comment by spacecowboy** [comment]
Yup. Long-standing issue.

**Comment by licaon-kter** [comment]
This looks like an *easy* fix though: make a full export on every sync.

**Comment by spacecowboy** [comment]
It's not with the current structure.

Issue is that everything is stored in a local database before exporting to the org-file, and the local database does not handle positioning during export.
