### ISSUE TITLE
How to un-complete a note?

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#312]
I can mark it as complete, say from a notification, but if i change my mind I can't find a way to unmark it.

I'm I missing something?

Android 5.1.1 w/ github free 5.7.0 apk

**Comment by spacecowboy** [comment]
There are several ways to toggle the state of tasks. One is the notification as you say. But then you have

- the list and
- the editor

Both of those are however predicated on the list being displayed as a "task list". Check your settings to make sure you have not configured the app to hide the checkboxes.

**Comment by licaon-kter** [comment]
Ok, I guess tasks are nice, I don't use them, but how about my issue as reported?

**Comment by spacecowboy** [comment]
Your statements are contradictory. Only tasks can be marked as complete.

**Comment by licaon-kter** [comment]
Well...

Note -> Reminder -> Notification -> https://i.imgur.com/r7kl6I1.png -> Press Complete -> Completed note -> https://i.imgur.com/vPnYWFj.png (that's a previously completed note)

**Comment by spacecowboy** [comment]
I should mention that notes and tasks are exactly the same thing.

The only way to reverse your action is to show the check boxes, as per my
previous instructions.

**Comment by licaon-kter** [comment]
All lists -> Lists -> Notes (long press) -> Show items as tasks -> and now the checkbox is visible

Kinda confusing, you can complete notes but you need to show them as tasks to un-complete them.

Not sure if I should close this issue or maybe try to suggest a better way to redesign this.

**Comment by spacecowboy** [comment]
The real issue you are reporting is `do not show'complete button' for notes, only show them for tasks` :)

**Comment by licaon-kter** [comment]
Ok, that's a way to look at it.

Better:
* Rename "Completed" to "Disable" or "Skip" or something like that that just removes the reminder (as is does now I guess)
* On "Disable" or "Skip" or whatever DON'T greyout the note (leave that only for tasks)

Sounds good?

**Comment by spacecowboy** [comment]
The reminder is already gone when the notification goes up, so just swipe it away.
The button should not be shown for notes, since it's mixing paradigms.

**Comment by licaon-kter** [comment]
I'd rather make the reminder removal an actual action, as in only when pressing "Disable"/"Skip"/whatever.
I would like that swiping away would not remove the reminder in the note but rather act like a longer snooze, say for 1 hour.

As I would rather be annoyed much later by a new notification than never.

**Comment by spacecowboy** [comment]
This is not how notifications are expected to work on android. See Google Calendar for example

**Comment by licaon-kter** [comment]
Google Keep does this, afaik, although now that I search the web this is rather a bug (?!), so ok do it as you see fit. :)

**Comment by spacecowboy** [comment]
Testing Google Keep reminder on a task list, I see two actions:

- In an hour
- Later

Both re-schedule the reminder, `later` opens a dialog so you can pick when. Swiping it away simply dismisses it.

The only difference between Keep and NN in this case is that NN deletes the reminder when it does this. This is due to internal implementation details. Note that Keep only allows you to have a single reminder for an item, whereas NN allows you to have an arbitrary number.

There is no difference in effort if you want to add another reminder to the item (for NN) versus modifying the existing reminder (for Keep).
