### ISSUE TITLE
Background sync for SD card?

### ISSUE THREAD

**Issue by benmoran** [spacecowboy/NotePad#313]
I'm using NoNonsenseNotes with org-mode export and Syncthing.  It works great when I manually do the SD sync, but is there a way to enable background syncing for SD tasks?  All the background sync settings appear disabled when GTasks sync is turned off.

Thank you so much for org-mode export,  I was desperately missing this option since MobileOrg seems to have run out of steam.

**Comment by spacecowboy** [comment]
The SD-sync is always running in the background. The app starts a sync everytime you start it up. And it should additionally schedule a sync everytime you update a note.

This isn't happening for you?

**Comment by benmoran** [comment]
Sorry, checked again and you're right!  Well that was easy. Thanks again.

**Comment by spacecowboy** [comment]
:+1:
