### ISSUE TITLE
Scroll down to search items?

### ISSUE THREAD

**Issue by Zheitk** [spacecowboy/NotePad#316]
What's the little arrow on the search results supposed to do? I was expecting to scroll me down to the selected item on a very long list, but it does nothing (android 4.1.1)

**Comment by spacecowboy** [comment]
If it's the arrow I think you mean, it is basically like hitting "return" on the keyboard, which is useless here I agree as the app automatically updates results as you type. But some apps dont do that.

**Comment by Zheitk** [comment]
Yes, basically it just removes the other search results O_o...
Then can this become a wish/suggestion ñ_ñ?
