### ISSUE TITLE
Material design branch ( version 6 ) issues

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#317]
Can we start reporting them?

Using free 6.0.0-beta.2:
* the list title is not shown: `side menu -> select a list or all lists -> list is open` but title is always **Notes**, while it should be **All Lists** or **list-name**
* you left only *task-type* notes, right? It's ok, better to have one type only, but my old *notes-type-list* is kept like that on upgrade, maybe it needs converting? Hey, even the *Add* function sees it like a *note* since there is no "Due-date" option
* on *Clear completed* maybe you can add a counter and add a different message when there are no completed tasks to be deleted
* in the share menu can you add *Copy to clipboard* or does the system decide what  options I get?
* do show app version number in About dialog 
* can you bring back https://github.com/spacecowboy/NotePad/issues/296 ?

Waiting for https://github.com/spacecowboy/NotePad/issues/310 , https://github.com/spacecowboy/NotePad/issues/306 , https://github.com/spacecowboy/NotePad/issues/303 :)

**Comment by spacecowboy** [comment]
Thanks for the feedback. Will get some of these fixed.

About 
> in the share menu can you add Copy to clipboard or does the system decide what options I get?

Android itself gives you this option in the share picker, so there is no need to implement it seperately in the app.

There will be a seperate title field in time (#296) but it will not have any configuration options.

If you find any more issues, feel free to comment on the pull request here: https://github.com/spacecowboy/NotePad/pull/311
it's where I track what needs to be done. I've added your points above to the list.
