### ISSUE TITLE
Use material design typography (specifically fonts)

### ISSUE THREAD

**Issue by spacecowboy** [spacecowboy/NotePad#318]

**Comment by CampelloManuel** [comment]
As of version 7.1.6, all references to fonts in the source code either don't specify the font family, or use Roboto.
Roboto is exposed to the user on a popup where the app's font can be chosen.
As of now we only offer Roboto as a choice, but i plan to explore possible alternatives, in the future.
Everything else uses the device's default fonts, which is the desired behavior.
