### ISSUE TITLE
 Make sure Share actions work

### ISSUE THREAD

**Issue by spacecowboy** [spacecowboy/NotePad#325]

**Comment by licaon-kter** [comment]
Receiving file/text ( like https://github.com/spacecowboy/NotePad/issues/33 ) or sharing task to another app?

Right now, although Notepad has the intent and can be selected for sharing, nothing happens.
In v5 a note would be created.

**Comment by spacecowboy** [comment]
Thanks. Created https://github.com/spacecowboy/NotePad/issues/346 for that. This was meant to make sure sharing to other apps worked as expected.
