### ISSUE TITLE
6.0 beta 2 crash on 4.4.4

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#333]
Starts ok, but:
* FC on start after I set the Sync folder (either an existing one with files or created one)
* FC on adding a task -> write some text -> press arrow to go back to list

I need to clear all app data to make it work again, although I can't actually use it for anything given these issues.

**Comment by spacecowboy** [comment]
Thanks, will have a look

**Comment by licaon-kter** [comment]
Confirmed, thanks.
