### ISSUE TITLE
Note title renders over title bar on 4.4.4

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#335]
I can repro on 4.4.4.
I can**'t** repro this on 5.0.2.

Steps:
- new task
- write a title ( I sure do hope you reimplement https://github.com/spacecowboy/NotePad/issues/296 :P )
- click on `Add a reminder`
- the UI shifts up with text with the wrong elevation

Screenshot:
![text over](https://i.imgur.com/ttPWEXN.png)

**Comment by spacecowboy** [comment]
Thx
