### ISSUE TITLE
6.0 beta - Empty title/first line becomes "TODO" on 2-nd resync

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#339]
Thought I could bypass the large first item thing (until you add https://github.com/spacecowboy/NotePad/issues/296 back ahem) by entering only a newline there, but noo, after a second resync/reload/reopen app a large "TODO" text appears there.

**Comment by spacecowboy** [comment]
Likely a bug in the parser. Created a linked issue
