### ISSUE TITLE
6.0 beta - Scrolling task should have a fixed titlebar

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#342]
I wanted it to be like [this](https://i.imgur.com/1BxkIkx.jpg), and I thought that's the default:
- image on left, see how the icon (list item) slides up under the title bar?
- image on right, see how the icon (list item) slides up from under the nav bar?

**Comment by spacecowboy** [comment]
Just to be clear, what is the app doing now that is not like this?

**Comment by licaon-kter** [comment]
No, on 5.1.1, the title bar scrolls up under the *statusbar*, while I expect it to be fixed and only the content to scroll under.

**Comment by spacecowboy** [comment]
This is a common pattern found in material design apps. You can read about it here https://www.google.com/design/spec/patterns/scrolling-techniques.html#scrolling-techniques-scrolling

Now whether or not it is the best design choice for this app is a more subjective discussion :)
But I think it's quite nice as it allows more content to be visible on the screen.

**Comment by licaon-kter** [comment]
*Flexible space with overlapping content* :)

I find it unhelpful as I finish adding items or setting reminders that now I need to scroll up to be able to get the back arrow visible.

**Comment by spacecowboy** [comment]
So you are referring to the Editor in particular then? And not the List?

**Comment by licaon-kter** [comment]
Yes, sorry if I did not make that clear from the start.

**Comment by spacecowboy** [comment]
Hmm, yeah I see your point in this case. Might change it and see how it feels.

**Comment by licaon-kter** [comment]
Actually it appears to have 2 modes now (6.0beta5):
* adding a reminder will scroll the view under the titlebar ( as I like it )
* scrolling the task by touch will scroll the view+titlebar under the status bar.

**Comment by licaon-kter** [comment]
Oh, now I see it, on a tablet is clearer.
You are using a *card view*, right?
Any reason to prefer that instead of, say *RecyclerView* (with *inneroverlay*) ?

**Comment by spacecowboy** [comment]
It's not a *card view* as implemented by Google. It's just backgrounds and stuff to make it look like a card. It was implemented before *card view* was available. Long term, I would really like to *RecyclerView all the things*.

The difference in scrolling behavior is likely due to CoordinatorLayout not responding to programmatic scrolling, which adding a reminder does.
