### ISSUE TITLE
Map does not appear for location-based reminders

### ISSUE THREAD

**Issue by svsen** [spacecowboy/NotePad#343]
When selecting the option for a location-based reminder, the map does not appear; the window area where the map should show up appears blank. However, location selection works as specified: long-pressing any part of the "map" area selects the address that is supposed to be there, and typing in an address in the location bar also selects the address (the reminder notification also comes up correctly when in the vicinity of the selected location). The map never shows up in any case. The device I am facing this problem on is Motorola Moto G 3rd Generation (XT1550). The Android version is 5.1.1. I have attached a screenshot that shows the problem.
![screenshot_nononsense-notes-map_2015-12-01-12-25-25](https://cloud.githubusercontent.com/assets/16106501/11512530/8ab81250-9894-11e5-9a41-bfa575192c47.png)

**Comment by licaon-kter** [comment]
Why is the location icon not showing up in the status bar either?

**Comment by svsen** [comment]
@licaon-kter That is a point to be noted too, thanks. I did not observe it earlier. My location setting is "high accuracy" and all other location-based apps are working fine.

**Comment by spacecowboy** [comment]
@svsen thank you for the clear report. I think I might know the fix for this issue and if it works I will release `5.7.2`. But I should mention that location reminders are getting removed in 6.0.0, to remove the dependency on proprietary google code.

Note to self: see if updating the API key does the trick
