### ISSUE TITLE
6.0beta - Notification reminder duplicate

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#345]
Steps:
- have a reminder
- screen off 
- reminder timeouts -> notification
- after some time (maybe longer than snooze time!?) open screen
- you can see the notification
- press complete

What should happen:
Notification disappears.

What actually happens:
Notification disappears but it's replace immediately by the same notification (with sound even).

I'll try to re-test to check what the task state is after the first complete press.

**Comment by spacecowboy** [comment]
:+1:

**Comment by licaon-kter** [comment]
So:
* completing the first notification marks task as completed in app
* notification look normal in lockscreen, but is darker with normal screen

**Comment by spacecowboy** [comment]
In other words, the task is completed correctly, but the notification is incorrectly "re-issued"?

**Comment by licaon-kter** [comment]
Yes.

**Comment by CampelloManuel** [comment]
fixed somewhere around version 7.1.0
