### ISSUE TITLE
Refresh indicator inconsistent

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#350]
Pull to refresh gets the normal material like indicator with animation.
Pressing refresh button yields a white circle or maybe the same indicator but it's animation is fast and disappears right away.

**Comment by spacecowboy** [comment]
It should be the same. Are you using SD-card sync here? That would explain why it's so fast.

**Comment by licaon-kter** [comment]
Yes, SD sync, but isn't it the same operation?

**Comment by spacecowboy** [comment]
The UI parts are the same yes, but what happens in the background is
completely different and SD Card sync is almost instant with little data.
So that explains why.

Still, it could be handled better in the UI (minimum time?) so we can keep
it open for now.

**Comment by licaon-kter** [comment]
Some sort of delay so they behave the same would be nice.
