### ISSUE TITLE
Task drag handle has too small touch target

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#351]
I find it hard to reorder tasks in list, not sure where I should touch and hold, I mostly move them around by mistake.

In v5 I could hold the vertical dots and it worked fine, now the hold point looks like it's a bit to the right, but when I try I end up selecting the task.

Am I doing it wrong or things changed here too?

**Comment by spacecowboy** [comment]
It was supposed to remain the same as before, more or less. The touch target probably got smaller when I tweaked the layout.
