### ISSUE TITLE
All notes lost

### ISSUE THREAD

**Issue by devurandom** [spacecowboy/NotePad#352]
All notes on my device are lost. I can still retrieve them from the archive, but that's a PITA. The same also happened a few days ago.

I have SD-Card-Sync enabled, but not Google-Tasks-Sync. I did not delete any messages recently. The phone reboots itself about daily, after it locks for a few seconds (I assume some watchdog triggers this, when the OS dead-locks).

This is on CyanogenMod 12.1 20151117-snapshot-yog7dao1k3-serranoltexx using NoNonsense Notes 5.7.2.

**Comment by licaon-kter** [comment]
So the *Notes.org*/*Tasks.org* files in **/sdcard/NoNonsenseNotes/** folder are empty?

**Comment by devurandom** [comment]
Right now there is a `/storage/sdcard1/NoNonsenseNotes/Tasks.org` file, which is about 1.9kB big. But I already restored the tasks from the archive.
