### ISSUE TITLE
Sync is either doesn't sync or it deletes notes

### ISSUE THREAD

**Issue by spacecowboy** [spacecowboy/NotePad#354]
Several reports.

There seems to be different behavior for new and old notes as noted by:

> No Nonsense Notes is deleting/archiving my new notes (any
> notes created over the last few days) on it's own??...and of course the new
> notes aren't syncing either. However any older notes I modify seem to sync
> fine.

and:

> I have a second list I use for tracking
> things but it no longer syncs them. I even deleted the second list and
> recreated from Google calendar with just one task in it. NoNonsense sees
> the newly recreated list but does not show the item in it. No errors appear
> when I try to sync from the app however, just nothing actually happens.
> 
> Changes I make to the default Notes list do sync properly between Google
> and NoNonsense

Possible duplicate #352

**Comment by 3dsman** [comment]
I have the same problem.
Sync to the sd card, not gmail.
