### ISSUE TITLE
(features) Week numbers and archive auto-deletion?

### ISSUE THREAD

**Issue by ghost** [spacecowboy/NotePad#359]
Hi, turns out i have two feature requests, both should be very simple.

The only thing i miss from the native Android calendar is the week number display on the left side of the calendar view, next to each weekly row. I use this at work quite often when making schedules, and i keep forgetting i can only see that from the native calendar currently. This would be a great addition to have and i wouldn't need the calendar any more at all.

Another, unrelated feature would be to have the archived (= trashed) messages auto-delete in five days? Seven? Alternatively all the notes in the "recycle bin" could be deleted with one button instead of one at a time. I use the program for a LOT of notes regularly, and the archive keeps filling up with deleted messages which i have to select individually in order to delete them again. With 40+ notes it's a job of it's own. :) Yet another alternative is a user-selected option not to archive deleted notes, meaning the first time you delete a note really means it's gone. Either way you think is best.

Thank you for the great app!

edit: forgot to add, i use F-Droid so if you happen to update the app, i hope you don't forget the F-Droid repos. 5.7.1 seems to be what i'm using, but i read somewhere there's a 5.7.2.

**Comment by licaon-kter** [comment]
Get 6.0beta5 free: https://github.com/spacecowboy/NotePad/releases because that's where things are now.

But you *need* to sync to sdcard, uninstall F-Droid version, install new version.
