### ISSUE TITLE
Edit note in landscape switches to light theme

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#362]
Use dark theme, rotate, yay light theme.

6.0beta5

**Comment by spacecowboy** [comment]
Thanks for the report.

**Comment by Akai-Karasu** [comment]
Regarding this, is it the fact that the keyboard is not showing in dark mode, as after finishing typing, the rest of the app is still in dark mode.

**Comment by spacecowboy** [comment]
No, I think it's just that the state change somehow doesn't load the correct theme
