### ISSUE TITLE
Import from Evernote

### ISSUE THREAD

**Issue by zhum** [spacecowboy/NotePad#364]
Hello!
I've started to use NoNonsense and I think it is very good. I want to move my notes from evernote to NoNonsense, but it seems there are no way to make it. I can export notes in enex or html format (I use text only), but I don't know how to import them to NoNonsense (I need to convert them into proper format and then I can import them from SD).

**Comment by spacecowboy** [comment]
Atm there is no way to import from evernote (or anything else tbh). Are you using NoNonenseNotes (NNN) with Gtask sync or SD card/Dropbox?

**Comment by zhum** [comment]
I user GTasks sync and it works.
