### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by Wirelesley** [spacecowboy/NotePad#372]
I use notepad every day and make about 10 notes a day. Sometimes more. It happens a lot that i get out of memory. App blockes. After restart. It works again. Because there is not a userfriendly  way to select and manipulate more messages at one

**Comment by Wirelesley** [comment]
Because there is not a userfriendly way to select and manipulate more messages at one time i do not clean up. Ones in a while i de-install and install again, to clean up.

**Comment by licaon-kter** [comment]
`Mark as completad-> Clear completed` is not enough?

**Comment by Wirelesley** [comment]
Please understand.
I take notes, dailey. And after a week or so I want to mark in one command al notes for deletion.
Quick view if all can be deleted, and then Delete all marked notes.

**Comment by spacecowboy** [comment]
@Wirelesley What about deleting the list, instead of the tasks? When you want to delete all of the tasks, just delete the list and start a new one.

**Comment by Wirelesley** [comment]
Thank you for your respons.
Now I went looking for an option to add or delete a list.
Then I found it. It was hidden on the sceen All tasks.

I selected the standard tasks en asked for deletion of my 2400 tasks.
It took some time and android responded with do I want to wait?
So I did.

But now I'm still waiting.

Erik Alers



Op Tue, 18 Oct 2016 11:21:24 +0200 schreef Jonas Kalderstam  
<notifications@github.com>:

>
> @Wirelesley What about deleting the list, instead of the tasks? When you  
> want to delete all of the tasks, just delete the list and start a new  
> one.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Gemaakt met Opera's e-mailprogramma: http://www.opera.com/mail/

**Comment by spacecowboy** [comment]
@Wirelesley 2400 tasks is an extreme case. If possible, I'd just reinstall the app at this time.

**Comment by Wirelesley** [comment]
Thats true.
Further, I think your App works quite well.
I never lost a note yet.

Thank you, soo far.

Erik


Op Tue, 25 Oct 2016 20:48:37 +0200 schreef Jonas Kalderstam  
<notifications@github.com>:

>
> @Wirelesley 2400 tasks is an extreme case. If possible, I'd just  
> reinstall the app at this time.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Gemaakt met Opera's e-mailprogramma: http://www.opera.com/mail/
