### ISSUE TITLE
Reordering tasks when sorting for "due date"

### ISSUE THREAD

**Issue by TheStealthReporter** [spacecowboy/NotePad#373]
Sometimes one task builds on another: for example "shopping (including ingredients)" should be done before "baking cake". Also I let the app order the tasks by their due dates to see what has to be done today or tomorrow separately.
It would be highly convenient to move tasks around in-one-day like one can with "manual sorting" so after rescheduling entries they can be handled from top to bottom.

It seems to work when switching from "sorting manually" to "sort by due date" (is that a bug?) but by restarting the app this feature is lost (is _that_ a bug?).

**Comment by spacecowboy** [comment]
> It would be highly convenient to move tasks around in-one-day like one can with "manual sorting" so after rescheduling entries they can be handled from top to bottom.

It is either due date, or manual sorting. I recommend you create new lists instead, for instance a list specific for all shopping tasks on a particular day, and use manual sorting from there.

> It seems to work when switching from "sorting manually" to "sort by due date" (is that a bug?) but by restarting the app this feature is lost (is that a bug?).

Not bugs, just undefined behavior. Tasks have no guarantees on the ordering of tasks due on the same day.

**Comment by TheStealthReporter** [comment]
With "working" I mean you can move tasks around _while_ you're in "due date"-sorting if you switched from "sorting manually".

**Comment by spacecowboy** [comment]
Ah, that's definitely a bug. But it's not present on latest beta version.
