### ISSUE TITLE
Add beta release tags

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#374]
So that F-Droid can build this and we can test.

**Comment by spacecowboy** [comment]
All releases are tagged. See https://github.com/spacecowboy/NotePad/tags

**Comment by licaon-kter** [comment]
Yes, ok, I was not clear enough.

The latest beta is almost 1 year old, I was asking for more beta tags, more often. :)

**Comment by spacecowboy** [comment]
Tags are added as things develop. If you look at the history, I've pretty much done nothing the last year. There is nothing new to release.
