### ISSUE TITLE
"Order manually" displays tasks in reverse order

### ISSUE THREAD

**Issue by bgainor** [spacecowboy/NotePad#375]
When using the "order manually" sort option, each list's tasks are displayed in the opposite order as the "my order" setting on Google's web interface.

App version: 5.7.1
Android version: 6.0
Device: Moto X Pure Edition

**Comment by licaon-kter** [comment]
better try the 6.0 beta 5 and report on that one.

**Comment by enrike** [comment]
same here. the tasks appear in the app exactly in exactly the opposite order they are in Google
App version: 5.7.1
Android version: 6.0.1
Device: Moto G Play

**Comment by licaon-kter** [comment]
See my comment above, also keep in mind this app is not developed anymore.

A new app can import these notes, is called: Orgzly, do try it.

**Comment by enrike** [comment]
oops... sorry I didnt see that
