### ISSUE TITLE
Remember position in note

### ISSUE THREAD

**Issue by Rudd-O** [spacecowboy/NotePad#381]
Sorely needed feature — when I go edit a note, the cursor should be exactly where I left it before (or an approximation thereof, if sync has changed the note).  Otherwise long notes are impossible to edit quickly.

**Comment by licaon-kter** [comment]
This is no longer developed

See https://github.com/orgzly/orgzly-android instead 

/PS: Did you test the beta? https://github.com/spacecowboy/NotePad/releases/tag/6.0.0-beta.5
