### ISSUE TITLE
what to to with orgparser

### ISSUE THREAD

**Issue by CampelloManuel** [spacecowboy/NotePad#395]
@spacecowboy I need your opinion on this one.
As of now we are using your library `org.cowboyprogrammer:orgparser:1.3.1` which is still only in `jcenter`.
To remove  `jcenter()` from the gradle file I need either to download `cowboyprogrammer:orgparser` from mavenCentral or to bundle it in this repository.

I think it's better if you upload it to mavencentral, like you did with the "no nonsense filepicker".
I just need version 1.3.1 to be available, the older ones can be ignored.

Let me know if this is okay with you.

**Comment by spacecowboy** [comment]
I can upload it

**Comment by spacecowboy** [comment]
I've started the process: https://issues.sonatype.org/browse/OSSRH-86090

**Comment by spacecowboy** [comment]
It has been released to maven central now @CampelloManuel . It may need a little while to become available but when it is it will be

    org.cowboyprogrammer.orgparser:orgparser:1.3.1

**Comment by spacecowboy** [comment]
https://search.maven.org/artifact/org.cowboyprogrammer.orgparser/orgparser/1.3.1/jar
