### ISSUE TITLE
what to do about google tasks

### ISSUE THREAD

**Issue by CampelloManuel** [spacecowboy/NotePad#403]
Google tasks sync does not work.

When trying to sync notes with google tasks, the code gives an `AuthenticatorException` with message `UNREGISTERED_ON_API_CONSOLE` after a google account is chosen.

The 5.7.1 version from f-droid shows no error message, but does not seem to work, either.

The app requires registration on an app console, but that requires a signing key, so I can't test it.

References:
* https://developers.google.com/identity/protocols/oauth2/native-app#creatingcred

**Comment by spacecowboy** [comment]
I agree. Google has tried to kill Tasks for years. So I think it's entirely reasonable to kill the integration and rely only on OPEN sync methods for future functionality.
