### ISSUE TITLE
enable updates on f-droid

### ISSUE THREAD

**Issue by CampelloManuel** [spacecowboy/NotePad#410]
the f-droid team disabled auto-updates for the app, as shown here:
https://gitlab.com/fdroid/fdroiddata/-/blob/84acda7e142b0365749acc9a981246f745d363b5/metadata/com.nononsenseapps.notepad.yml#L178-179
So we have to contact them once we have a new version ready to be published. 
This https://gitlab.com/fdroid/fdroiddata/-/blob/203ce022ecd15b87d9d96a43397f4d61e2f17ed3/metadata/io.github.quillpad.yml shows how the file should look like. 
Open the issue for inclusion as explained here https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#updating-apps-already-in-f-droid
See https://gitlab.com/fdroid/rfp

Then we go back to work on #387

**Comment by spacecowboy** [comment]
Sure. It's not so much contacting them as making a PR  with updates to https://gitlab.com/fdroid/fdroiddata/-/blob/84acda7e142b0365749acc9a981246f745d363b5/metadata/com.nononsenseapps.notepad.yml#L178-179

I'll have a look at the app

**Comment by spacecowboy** [comment]
OK I installed it in an emulator and it seems to work fine.

Some thoughts:

* There are some lint checks failing, namely some translated strings that no longer exist in `values/strings.xml`. These entries should just be removed
* The Google Tasks setting still exists in settings/synchronization. This should probably be removed completely so users don't think it's coming back
* Settings/About still reference https://crowdin.com/project/nononsensenotes . Not sure if you want to keep using that. Personally I find that Weblate is a better service. Maybe remove this link?
* Settings/About maybe give yourself more credit than Special Thanks? Your choice, but I think a succinct `Maintained by` would be more to the point.

Once you feel really ready to make the release, make an annotated git tag (or create a release here on github, same thing really) and I'll make a PR against F-Droid to re-enable it.

Oh and here is the metadata file. Just waiting on the git tag and your go-ahead. 
https://gitlab.com/spacecowboy/fdroiddata/-/commit/6a0fe29aa6352faec0c5f74de65f50fa96e8f15e

**Comment by spacecowboy** [comment]
> Is it something where we can import updated strings.xml files every once in a while, or does it require more attention ?

Weblate is nice because it creates a pull request automatically with the strings.xml changes. So it's extremely low attention once it is set up. I can help with it later if you want.

> Checked. I made a simple fastlane structure, I don't know if f-droid will use it. It includes an app description.

F-Droid will use the app-specific description if it exists. 

F-Droid MR here also: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12209

**Comment by spacecowboy** [comment]
I've updated the F-Droid MR. Just waiting on `7.0.1` for the final change @CampelloManuel

**Comment by spacecowboy** [comment]
F-Droid has merged the MR so it will show up soon!

**Comment by spacecowboy** [comment]
> Well, there it is. @spacecowboy is there anything else we need to do for f-droid, or will they automaticall publish the updates when we make new tags ?

Should happen automatically from now on. I can recommend a small shellscript or similar which bumps versionCode, versionName, and then makes a git tag.

It's easy to forget one of the three.
