### ISSUE TITLE
publish the app on google play store

### ISSUE THREAD

**Issue by CampelloManuel** [spacecowboy/NotePad#411]
@spacecowboy is there something I need to do on the repository to prepare for the play store ?
Are you going to handle the publishing process ?
If you want, I can try to do it, but I have never published on the play store before, so I have to setup everything.

**Comment by spacecowboy** [comment]
You can't publish it since I control the package name.

I can look into automating it with fastlane.

**Comment by spacecowboy** [comment]
@CampelloManuel can you email me an address which I can grant access for the play store?

you can send it to

jonas at cowboyprogrammer.org

**Comment by CampelloManuel** [comment]
When we publish the app on the play store, I would like it to remain free, as in "without a price".
If you want we can integrate some crowdfunding platform, but I think it should remain optional.
I see that you have other free apps on the play store, so this will not be a problem, I imagine ?

**Comment by spacecowboy** [comment]
> When we publish the app on the play store, I would like it to remain free, as in "without a price". If you want we can integrate some crowdfunding platform, but I think it should remain optional. I see that you have other free apps on the play store, so this will not be a problem, I imagine ?

Of course it should remain free.

Also I'm thinking we should add a gradle flavor with another applicationId ending in `.play`. It's good practice to have a different applicationId in different stores.

This will also enable me to generate new release keys to be used for the app, and share those with you.

**Comment by CampelloManuel** [comment]
Oh, I see. I'm afraid I deleted the `play` flavor when I was removing non-free components and dependencies. I'll try to add it back, before the next release.

> It's good practice to have a different applicationId in different stores

May I ask why ?

**Comment by spacecowboy** [comment]
> > It's good practice to have a different applicationId in different stores
> 
> May I ask why ?

It's convenient to be able to install from both stores at the same time. Usually only something a developer wants to do.

But ensures that people don't install from F-Droid, and then get errors from Play store saying it can't update the app or vice-versa.

But primarily it's so I can use a new key on the play store.

**Comment by CampelloManuel** [comment]
I added a new `playStore` build variant with package id = `com.nononsenseapps.notepad.play`.
Now, about this key you have to make, 
is this something you can do on the repository before compiling, 
or do I have to create a new github release ?

I can make a new release (7.1.4) even now, if you need it.

**Comment by spacecowboy** [comment]
I've published 7.1.3 on the play store: https://play.google.com/store/apps/details?id=com.nononsenseapps.notepad.play

The automatic pipeline just needs a bit more because I accidentally used the wrong key for the first pipeline. The correct key will be possible to be used on Jan 25th so I'll merge after that

https://github.com/spacecowboy/NotePad/actions/runs/3981806695/jobs/6830841756

**Comment by CampelloManuel** [comment]
Ok. 
Once you merge that, we can release the new 7.1.4.

To publish future updates on the play store, what do I need to do ?
Do I just have to run a script, or is there more to it ?

**Comment by spacecowboy** [comment]
> Ok. Once you merge that, we can release the new 7.1.4.
> 
> To publish future updates on the play store, what do I need to do ? Do I just have to run a script, or is there more to it ?

Nothing at all. Make a tag and push it. The fastlane pipeline will be configured to run on (all) tags.

**Comment by CampelloManuel** [comment]
By releasing the 7.1.5 update on the play store I confirm that:
* the publishing process works automatically
* the play store version can be installed alongside the fdroid version
* we just need to be careful of new translations: fastlane needs all 3 txt files for ALL languages
