### ISSUE TITLE
Removing crowdin translations

### ISSUE THREAD

**Issue by CampelloManuel** [spacecowboy/NotePad#432]
Now that we are on weblate https://hosted.weblate.org/engage/no-nonsense-notes/
I think we should close the crowdin page, or at least make it clear for users that they have to go to weblate instead.

When looking at the crowdin page https://crowdin.com/project/nononsensenotes/activity-stream
I noticed some activity in 2019 and 2017 but I can't access the xml files, maybe because I don't own the project on crowdin.

I think it's worth it to import the translations manually from crowdin, just once, and then remove NoNonsenseNotes from crowdin

**Comment by comradekingu** [comment]
It breaks all sorts of terms and agreements to route translations (of other people) from elsewhere into Crowdin.
The terms on there are agreed to individually by the translator using Crowdin, and it is a spaghetti mess of spying and misuse.

**Comment by spacecowboy** [comment]
> @spacecowboy I can't download the translations from crowdin (maybe I'm just blind).
> 
> If you download and send the files to me I can merge them in the app repository, or you can just delete the crowdin page, but we will lose all new translations from 2017~2019.
> 
> What do you want to do ?

[NoNonsenseNotes (translations).zip](https://github.com/spacecowboy/NotePad/files/10207889/NoNonsenseNotes.translations.zip)

Here are the built files from crowdin. 

I'll go ahead and delete the project now
