### ISSUE TITLE
Norwegian translations

### ISSUE THREAD

**Issue by CampelloManuel** [spacecowboy/NotePad#451]
From weblate we got this file https://github.com/spacecowboy/NotePad/blob/master/app/src/main/res/values-nb-rNO/strings.xml for the `nb-rNO` locale.

From crowdin we got this https://github.com/spacecowboy/NotePad/blob/master/app/src/main/res/values-nn/strings.xml for the `no-rNO` locale, and then I moved it to `nn`

Now, I don't know either language, but they seem different enough to me.

@comradekingu  can I get your opinion on this ? Do you recommend I delete one, or can I keep both ? Are both languages useful ?

I think we can either:
* wait for users to update both translation files on weblate
* remove `values-nn/strings.xml` which is outdated

**Comment by CampelloManuel** [comment]
as of now, the app recognizes them as 2 different languages, and some strings **are** different, tough for all I know, they could be synonims.
If there are problems with the current translations, volunteers on Weblate will fix the translations.

Since it's not a problem, I'll close this issue.

**Comment by comradekingu** [comment]
Crowdin uses the wrong locale by default.
Norwegian Bokmål (which already exists) should be `/nb-rNO`.
`nn` can be deleted.
