### ISSUE TITLE
Filesystem access

### ISSUE THREAD

**Issue by CampelloManuel** [spacecowboy/NotePad#454]
We have to find a way to keep SD sync and json backup working. 
This issue details all problems related to filesystem access

For android API >= 29 the `File` API used everywhere in this app does not work: we can't save backups in Downloads/ , it says "file not found". But in `Android/data/.../` it works.
For android API < 29 it works but needs the WRITE_EXTERNAL_STORAGE permission.

The recommended solution is to replace file access with DocumentFile, using the Storage Access Framework and the system's built-in filepicker. Already finished for the json backups, but the org files will keep using the `File` API: the code uses File objects instead of URIs, so enabling this is just too much work.

We use an hardcoded folder, `/storage/emulated/0/Android/data/packagename/files` for ORG files. 
* That folder is the least likely to cause problems
* no need to change most app code
* Users can stil manually move and edit org files with their file manager app
* if someone needs the content of those ORG files we can add an on-demand export function or an android content provider to query the note data
* easier to use, no folder to choose

An attempt was made to use the `MediaStore` API, but it was too unreliable and discomfortable to use.
Interested readers can look for `MediaStoreHelper` in #455 
Where the `File` API is blocked by Google, we use the Storage Access Framework

**Comment by est61** [comment]
> We use an hardcoded folder, `/storage/emulated/0/Android/data/packagename/files` for ORG files.


Hi @CampelloManuel  @spacecowboy 

This is a problem, as on Android 16, i am unable to access Android/data with syncthing(BasicSync) like i did in Android 10, so i can no longer sync that dir, and neither can i change the file path of the notes.

Is it possible you can allow the user so that they're able to change their storage to wherever they want instead of hardcoding it?

I love this app and I really dont want to move to another notes app just because of this issue

**Comment by CampelloManuel** [comment]
@est61 yes it is possible, for example we could ask the user to pick a folder to save the org files.
However, I don't have time to dedicate to this feature.
I focus on basic maintenance to ensure the core features keep working on newer Android versions.
I will review and accept pull requests, but I can't promise I will implement this feature in the short term.
