### ISSUE TITLE
Notifications have no "snooze" or "completed" options 

### ISSUE THREAD

**Issue by urmomsangus** [spacecowboy/NotePad#478]
### Describe the bug

Reminder notifications have no "snooze" or "completed" options despite enabling all notification options.

### how To Reproduce
 
Create a reminder and receive a notification. Notification can be swiped away but it has no option to snooze or mark it for completion.

### Technical information

Samsung Galaxy A53, Android 12

**Comment by CampelloManuel** [comment]
* do other apps show buttons on their notifications ? for example, the telephone app could have buttons to answer an incoming call, the sms app could have buttons for quick replies, ...
* when you set the reminder on the note, are you editing a "task" or a "note" ? the difference is that you can set the due date on a "task" but not on a "note"
* if you "slide down" on a notification, as if to expand it, do these buttons appear ? For example, in my galaxy a50 you have to press the arrow on the right to see the buttons:


![Screenshot_20230107-210025_NoNonsense Notes](https://user-images.githubusercontent.com/9112949/211168413-87bef6f5-092e-4027-b725-5706f7e459db.jpg)

and then the buttons appear.

* did you also check the system settings for the notification channel ?

**Comment by urmomsangus** [comment]
> * do other apps show buttons on their notifications ?

Yes, another Tasks app I have shows complete & snooze, and other apps with intended buttons have buttons in the notification also.

> * when you set the reminder on the note, are you editing a "task" or a "note" ? 

I was aware of this and ensured I was testing with Tasks only.

> * if you "slide down" on a notification, as if to expand it, do these buttons appear ? 

No they do not.

> * did you also check the system settings for the notification channel ?

Yes, I did. All notification options and categories are set correctly. Also Exact alarms and Exact reminders enabled in app settings, and battery optimization turned off.

**Comment by urmomsangus** [comment]
I did a bunch more testing, and I think only repeating reminders (click on the day to highlight the day) don't show the buttons. 
 
For some reason I hadn't tried non-repeating ones (thought I did).

Not sure if that's a feature or still a bug. It would help if any other users can confirm the behavior.

To clarify, I now have buttons when choosing a non-repeating reminder.

**Comment by CampelloManuel** [comment]
Ah, yes, I tested and now I can confirm. The buttons are only for non repeating notes. Reference:

https://github.com/spacecowboy/NotePad/blob/0c6474a91bab473b4e35dc4f64488b1b073cd113/app/src/main/java/com/nononsenseapps/helpers/NotificationHelper.java#L396-L403

So this issue turns into 2 feature requests:
* [ ] show the "complete" button even on periodic reminders. This one seems useless, though. Does anyone really need to set "complete" a periodic task from the notification ? The only time anyone presses this button would be by mistake! (in my opinion)
* [ ] show the "snooze" button even on periodic reminders. in this case, pressing it would add a new reminder, only for the current day, 30 minutes in the future. This seems useful: maybe you add a reminder to drink water every day, but right now you can't take a break so you snooze the reminder, to show it in 30 minutes, without altering the reminder for tomorrow

I'd like you opinion on this. Given that non-repeating reminders are OK, 
which buttons do you want to see on notifications for repeating reminders ?

**Comment by urmomsangus** [comment]
I agree, you do not need a "complete" button on repeating reminders, at least the way the app is designed right now. 

What I mean by the way it's designed right now:

- If for some reason you ever choose to make setting the "Due date" generate a reminder for the due date itself, the argument could be made that having a "Complete" button would work as then the task could reschedule and eventually show on "Next 5 days" list.
- A separate notification enhancement that could be beneficial is "persistent reminders," reminders that cannot be accidentally swiped away. If that was implemented, a "Complete" button would be the only way to dismiss the reminder but in theory not actually mark it as "complete" in the app. (The idea being that it is harder to accidentally hit a "complete" button than it is to accidentally swipe away the notification.)

A snooze button on repeating tasks would work out very well if it follows the same behavior as snooze for non-repeating tasks.

**Comment by CampelloManuel** [comment]
> persistent reminders

Yeah I remember seeing an old feature request about this. 
I added it as a **secondary** task for this project. 
Implementing repeating reminders every X weeks will take precedence, though.
Also, while I have not yet looked into this, I'm sure Google did something to make this either impossible or extremely hard to implement. We will see.

> A snooze button on repeating tasks

Will be implemented in the near future. 

---

As everything causing this issue was cleared and/or added to the #387 I will close this issue

**Comment by urmomsangus** [comment]
> > persistent reminders
> 
> Yeah I remember seeing an old feature request about this. I added it as a **secondary** task for this project. Implementing repeating reminders every X weeks will take precedence, though. Also, while I have not yet looked into this, I'm sure Google did something to make this either impossible or extremely hard to implement. We will see.

Thanks for everything.

Here is a Commit *fixing* **persistent** notifications in another app. I'm hoping this might give you a trail to follow to see how it's implemented, should you choose to implement it in the future.

https://github.com/tasks/tasks/commit/dd48d074bea72d39e9a6721d442611b8500e5ae4
