### ISSUE TITLE
the github sponsor feature

### ISSUE THREAD

**Issue by CampelloManuel** [spacecowboy/NotePad#486]
A few questions for @spacecowboy

When I decided to update No Nonsense Notes, someone recommended that I take a look at this repository https://github.com/OpenTracksApp/OpenTracks for inspiration. I see that they have a "funding button" for sponsors.

I added something like that in https://github.com/spacecowboy/NotePad/blob/master/.github/FUNDING.yml
and it looks like (only) you can enable it in the repository settings.

Now, this is my first open source project that I'm contributing to, so I don't know what the common practices or technologies are, in relation to funding.
what do you usually do about this ? 
Do I have to add something else as funding platform ? 
Is this something that we should ignore altogether ?

I just want to know what you think about this

**Comment by spacecowboy** [comment]
Of course.

I am on `Ko-fi` myself. Which platform(s) are you on? I can make sure to enable this

**Comment by spacecowboy** [comment]
I've enabled the sponsor button now

**Comment by CampelloManuel** [comment]
> Which platform(s) are you on?

Over time, I made an account to try both ko-fi and liberapay:
https://en.liberapay.com/CampelloManuel/
https://ko-fi.com/campellomanuel

I think the _github sponsors_ link is sufficient for my account, maybe I'll add one of the 2 links I mentioned, but it's not a priority for me.

> I've enabled the sponsor button now

Good, thank you. I added your username on https://github.com/spacecowboy/NotePad/blob/master/.github/FUNDING.yml but it seems you need to connect your account to `stripe` in order to take advantage of this github sponsors thing.

I left a link to the tutorial on the yml file, so you can make a commit and add your links.

Then, I think, we can close this issue
