### ISSUE TITLE
Widget not updating

### ISSUE THREAD

**Issue by dominikbell** [spacecowboy/NotePad#490]
### Describe the bug

The widget is not updating when adding items to the lists. The lists themselves update as can be checked by opening the app. Removing and readding the widget brings it up to the latest status. As far as I noticed, this bug only occurred after upgrading from LineageOS 19 to 20 (c.f. below for technical details).

### How To Reproduce

1. Click "+" on widget
2. Write something
3. Click back arrow on top left
4. See item in app
5. Exit app
6. Don't see item in widget

Expected result: 6. See item in widget

### Technical information

- Device: OnePlus 9
- OS: LineageOS 20.0
- app version: v7.1.3

I'm using the following settings for the widget (if that is relevant): list=tasks, sorting=manual, theme=dark, transparency=default, max_height=default, hide_checkboxes=False, hide_due_date=False, hide_entire_widget_header=False

**Comment by CampelloManuel** [comment]
Yeah it does that, sometimes.
What launcher are you using? the default one from lineageOS or another app ?

Anyway, I will look into this in the next weeks.

**Comment by dominikbell** [comment]
Yes the default launcher. Although now I have noticed the same behaviour for widgets of other apps, so maybe the bug is related to lineageos and not this app.

**Comment by CampelloManuel** [comment]
if you could try the widget with some other launchers, like "simple launcher" or "lawnchair" or whatever you find on f-droid (or the play store), it would be very helpful to me.
I don't think a logcat will help here, so I won't ask for that.

**Comment by dominikbell** [comment]
I have been using the [Simple Launcher](https://github.com/SimpleMobileTools/Simple-Launcher) for a few days now, and I haven't experienced the same issue since. The only weird thing is that when I restart my phone, the widget says "loading" but is never loaded, so I have to remove it and readd it to the home screen.

Let me know if I can provide any logs or other technical details for you to fix the issue.

**Comment by CampelloManuel** [comment]
> when I restart my phone, the widget says "loading" but is never loaded

Yeah I think I inherited that bug from an old version of the app. I'll try to fix it, but since I rarely restart my phone I don't consider it a priority.
I can replicate the issue, so I don't need logcats (for now).
Fixing this may take a long time, because I have to focus my attention on other projects, at the moment.
Anyway, thanks for your help so far.

**Comment by dominikbell** [comment]
Btw, this bug has been fixed by updating to the latest LineageOS build.
