### ISSUE TITLE
Add Lists view

### ISSUE THREAD

**Issue by A-7666** [spacecowboy/NotePad#498]
**Is your feature request related to a problem? Please describe.**
There is no lists view (the screen with the list of lists).
When I open a ToDo list program, I would expect it to be the default / first screen I see.

**Describe the solution you'd like**
Add list view (the list of lists), set it as default view

**Comment by CampelloManuel** [comment]
the list of note lists is in the drawer menu.
Not showing a list of lists when the app starts is a design choice which we are going to keep.
See the tutorial https://github.com/spacecowboy/NotePad/blob/master/documents/TUTORIAL.md for more info on how to navigate the app

**Comment by CampelloManuel** [comment]
I'll close this, since I'm not going to add a "lists view" in addition to the app drawer
