### ISSUE TITLE
Make it possible to have smaller on-screen size (height) of items/entries

### ISSUE THREAD

**Issue by RedSteel-1** [spacecowboy/NotePad#500]
**Is your feature request related to a problem? Please describe.**
List entries are way to big, and changing the text size doesn't change their height.
And the side menu entries are especially big, just giant.
Too much space is lost for nothing

**Describe the solution you'd like**
Add an option to set a small and very small list and side-menu entries size/height, so that more of them fit on the screen.

**Comment by CampelloManuel** [comment]
just fixed in eaafdc3c8ae22a39d6eeb8071353f399ead9d1c9 it will be available in the next update, which should reach the app stores in a few days
