### ISSUE TITLE
remove animation in the app

### ISSUE THREAD

**Issue by OmlineEditor** [spacecowboy/NotePad#501]
I have completely removed the animation of all windows, animation is enabled in your application by default, and this greatly interferes. please add an option to the settings to turn off the animation

**Comment by CampelloManuel** [comment]
Do you think it's good enough if I just remove all custom animations from the app ?
I mean there's just 8 files, most don't even seem to be used, personally I don't **need** animations, and it's easier to just delete the files.
So the app will use the default animations, which you can then disable in the system settings.
Sounds good ?

**Comment by OmlineEditor** [comment]
great idea. do it

**Comment by CampelloManuel** [comment]
@OmlineEditor the new update disables animations in the app when you set `animation scale` to `0x` in the developer settings. Try and see if it works for you

**Comment by OmlineEditor** [comment]
ok, I'm waiting for the new version on F-Droid.

**Comment by CampelloManuel** [comment]
Did you try the new version on f-droid ?
I confirm that on my device it has no animations.

I would like some feedback, or I'll close this issue in a few days

**Comment by OmlineEditor** [comment]
I've seen the new version 7.1.6, but nothing has changed there.
I'm still waiting for the new version where the animation will be removed

**Comment by CampelloManuel** [comment]
I tested version 7.1.6 and I can't see animations. I disabled animations in the developer settings. 

Maybe you disabled animations in the accessibility settings ?

What elements of the user interface are still animated in your device ?

**Comment by CampelloManuel** [comment]
with eccf2722cdf85d7f7e9629e4ff12f288caa9ad23 all those animations are now disabled. The new behavior will be in update 7.1.7 in a few days
