### ISSUE TITLE
Repeating reminders can't handle the switch between DST and ST

### ISSUE THREAD

**Issue by CampelloManuel** [spacecowboy/NotePad#509]
### Describe the bug

When Daylight Saving Time (DST) ends and Standard Time (ST) resumes, some reminders end up with the wrong hour:
* [x] reminders that trigger only once correctly handle the switch from DST to ST 
* [ ] repeating reminders have their due time decreased by one hour when switching from DST to ST
* [ ] when switching from ST to DST, repeating reminders are set 1 hour later than expected

### how To Reproduce

1. Set a repeating reminder on a note when DST is active, with due time set to 8:00
2. wait for DST to end and for ST to resume
3. open the note with the repeating reminder
4. you will see that the due time is set to 7:00. This is not a design intent, it should remain to 8:00

### Technical information

- Device: any
- OS: android 11
- app version: 7.1.6

First noticed on 30 oct 2023

Since this only affects repeating reminders, it's possible that a bugfix from the "once only" reminders did not get implemented, so start by looking for differences in how those 2 kinds of reminders are handled.
Also, the obsolete `Time` class should be replaced with the new `GregorianCalendar`, as requested in #380 , before investigating bugs involving time, like this one

## Update

the bug is most likely in Notification.java in `public void deleteOrReschedule(final Context context) {`

**Comment by kayronnBR** [comment]
Put options to search for specific text within the note

**Comment by CampelloManuel** [comment]
@kayronnBR is this a new feature request ?
Do you want me to add a feature to let you search a word and then select it in the note editor ?
If your notes are so long that you need a search function to navigate them, you should consider making a list of notes. Then, divide the longest notes in parts, and it will become easier to find your content.

Also, I assume your comment is not related to daylight saving ?
