### ISSUE TITLE
How to restore?

### ISSUE THREAD

**Issue by myfirstnameispaul** [spacecowboy/NotePad#510]
I have installed via F-Droid to create backup with LineageOS. Now trying to restore backup via install from F-Droid in GrapheneOS, and finding that there isn't a restore option in the app.

How do I restore?

**Comment by CampelloManuel** [comment]
To make a backup of the notes (as a json file):
1. open the app --> open the 3 dots menu --> go to "settings" --> go to "backup"
2. touch the 1° option to choose a backup folder
3. choose the folder with your file picker
4. you're now back to the app: touch "export backup"
5. you now have a json file with the notes

To RESTORE a backup from a json file
1. open the app --> open the 3 dots menu --> go to "settings" --> go to "backup"
2. touch the 1° option to choose a backup folder
3. pick the folder that contains the json file
4. you're now back to the app: touch "import backup"
5. your notes should now be in the app

I have tested this procedure and it works.
Maybe you renamed the json file ?
It should remain with the name "NoNonsenseNotes_Backup.json"

**Comment by CampelloManuel** [comment]
@myfirstnameispaul 
I assume you managed to restore your notes ?
I will close this issue in a few days.
