### ISSUE TITLE
Notes disappear when sorting by date

### ISSUE THREAD

**Issue by JJ840** [spacecowboy/NotePad#525]
### Describe the bug

Notes disappear when sorting by due date and don't show up. They aren't lost and return when sorting via another method, but the only thing that shoes up when sorting by due date is the day headers and not the actual items.

### how To Reproduce

Open left hand menu
Long click on a list
Sort by Due Date

### If applicable

* add the stacktrace
* add logcat output as explained [here](https://f-droid.org/docs/Getting_logcat_messages_after_crash/)

### Technical information

- Device: Pixel 6 Pro
- OS: GrapheneOS 2024020500
- app version: 7.1.7
- app commit id (only for nightly builds): 

Sorting via the 3 dots menu on the upper right also doesn't change the sorting method.
Tried backing up and restoring, didn't change anything.

**Comment by CampelloManuel** [comment]
i tried making a list and sorting by date, but i can't replicate. This happens in the app, not in the widget, correct ?

i will try it on other devices in the future, to see if i can replicate.

> Sorting via the 3 dots menu on the upper right also doesn't change the sorting method

that menu is a placeholder, the feature is still a work in progress

**Comment by CampelloManuel** [comment]
I can't replicate.
I will publish an update in a few days.
Can you try uninstalling the app, installing that update, and rewriting the notes to see if it still happens ?

**Comment by CampelloManuel** [comment]
@JJ840 update 7.1.8 is now available. Can you verify if the bug is still present ?

**Comment by JJ840** [comment]
Yeah, I'm still experiencing it. I'm wondering if my notes file is just corrupt, but it still doesn't work when I add new notes. Very weird.

Jun 22, 2024 5:47:07 AM Campello Manuel ***@***.***>:

**Comment by CampelloManuel** [comment]
I can now replicate this on a Google Pixel 8a with the stock rom on Android 14.
Hopefully I can fix it.

**Comment by CampelloManuel** [comment]
@JJ840 update 7.1.9 is now available on f-droid and the play store. The bug with the dates should be fixed. Can you try the app and tell me if it works ?
