### ISSUE TITLE
Notes sorting descending order for sorting categories (A-Z,time, due date)

### ISSUE THREAD

**Issue by HusniMuhammad** [spacecowboy/NotePad#527]
**Is your feature request related to a problem? Please describe.**

I want to see notes that too old first in Both app and widget 

**Additional context**

![Screenshot_20240320-061254](https://github.com/spacecowboy/NotePad/assets/104101867/809ad480-d632-4ea5-a7fc-a9373e1a9e82)

**Comment by CampelloManuel** [comment]
oh and by the way you have to go to the drawer menu on the left to set manual ordering, not the overflow menu, that one says that the feature is *work in progress*

**Comment by HusniMuhammad** [comment]
Thanks
