### ISSUE TITLE
Using touch gesture to reorder notes

### ISSUE THREAD

**Issue by HusniMuhammad** [spacecowboy/NotePad#528]
**Is your feature request related to a problem? Please describe.**
I want to reorder my notes

**Describe the solution you'd like**
Using touch gesture to reorder notes similar to Android tiles (for notes app it's applicable (practically) for two direction (up-down, down-up)

**Comment by CampelloManuel** [comment]
If you set manual ordering you get a "grip object" on the side. It looks like this:
![tut10](https://github.com/spacecowboy/NotePad/assets/9112949/8be1b37e-8b1a-4514-b08d-581739db7b14)

you can then hold it and drag the note to move it up or down the list.

**Comment by HusniMuhammad** [comment]
Not showing

**Comment by CampelloManuel** [comment]
once you set *manual ordering* then you have to drag the notes with your finger.
In the app I can drag notes up and down, and it saves the manual order when you exit and return to the app.
But you have to manually order the notes once you choose *manual ordering*.

Does this solve the issue ?

**Comment by HusniMuhammad** [comment]
> once you set _manual ordering_ then you have to drag the notes with your finger. In the app I can drag notes up and down, and it saves the manual order when you exit and return to the app. But you have to manually order the notes once you choose _manual ordering_.
> 
> Does this solve the issue ?

Worked, thanks :)
