### ISSUE TITLE
synchro. with nextcloud

### ISSUE THREAD

**Issue by kolomo0** [spacecowboy/NotePad#529]
Hello,
Is it possible to have synchro. with nextcloud, or webdav, or nextcoud notes ?
So, we can have the same notes on two different devices.
Thank you for the app. I like the simplicity.

**Comment by CampelloManuel** [comment]
WebDAV is being considered, but I am not actively developing it, beacuse I would not use it very much.

Progress is tracked in #513 

If you want a notes app that can sync with web services, I recommend looking for alternatives like Orgzly or Google Keep
