### ISSUE TITLE
Beginning in note body instead of title when creating new note (and too small text)

### ISSUE THREAD

**Issue by krwow** [spacecowboy/NotePad#533]
**Is your feature request related to a problem? Please describe.**
I'm a bit dissatisfied with current note creating. It always starts with title instead of note content and there's no distinction between these two, they are not two fields, but title is always the first line and note body is the following lines.

**Describe the solution you'd like**
First of all, I'd like to have an option to choose if I can start typing in a note title or a note text. If making note in a hurry, it's better to write down note content and worry about title later. Now it takes a moment to write anything and go to the next line or switch to the second line straightaway to start writing note as text, in a normal-sized font. So I'd split title and note text into two text fields. To make it more clearly visible, adding two placeholders like in html would be a great idea. One extra, probably something like "Title" to the existing "Note" in light grey in respective text fields before writing own content. And there should be a bit more space between these two field than it's now, because at this moment if not for a different font size, title would be just like another line of a text, without any distinction between title and text. For example half of height of empty line would be a good separator between these two.

**Describe alternatives you've considered**
Another approach is to set the same font size for each line and then it would up to user how to treat some part of text as a title - some would still use the first line as title, other would add one empty line after title to make more clear distinction between these two. Then it settings there could be an option to display x lines of each note on notes list (main screen) and that's it. But I think it would be less elegant, having actually no title with another font at all. And a bit offtopic - an option to change (to increase) font size in notes list view would be appreciated as well.

<!--**Additional context**
Add any other context or screenshots about the feature request here--!>

**Comment by CampelloManuel** [comment]
Hi, thank you for your input.

> Another approach is to set the same font size for each line and then it would up to user how to treat some part of text as a title

>  there could be an option to display x lines of each note on notes list (main screen

You can already set these in the app settings.

> an option to change (to increase) font size in notes list view would be appreciated as well.

I think the user should increase the system font size in android's accessibility settings, for a more consistent text size across all apps.

---

My opinion on note taking apps is that there are many of them, even on f-droid, that are just slight variations on the same concept, and you pick the one you prefer. The division between title and body that you describe is already implemented in other note taking apps. I remember seeing one like that a few years ago. I'm sure you will find it on f-droid. That's not what I want for this app.
