### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by mariush444** [spacecowboy/NotePad#547]
It would be great to have option UNDO the last change.

**Comment by CampelloManuel** [comment]
A summary of undo features available in the app:
- You can undo (and redo) your edits to the note as you're typing, that's a feature in some keyboard apps, for example FUTO keyboard.
- You can restore the text in previous versions of the note: open a note, tap the 3 dots menu, tap *time machine*, move the blue slider until you find the version you want to restore, and click DONE.
- You can restore deleted notes: open the app, tap the 3 dots menu, tap archive, tap the notes you want to restore, tap RESTORE, choose the list to save them into, and tap OK
- To undo changes such as moving a note into another list, you have to manually move the note back

I can't think of something else to add. I admit the [tutorial](https://github.com/spacecowboy/NotePad/blob/master/documents/TUTORIAL.md) needs some work. See #549

**Comment by mariush444** [comment]
Really impresive, sorry that I didn't know that.
