### ISSUE TITLE
Could not find/read backup file

### ISSUE THREAD

**Issue by dekiesel** [spacecowboy/NotePad#552]
### Describe the bug

Backup doesn't get imported.

### how To Reproduce

1. I created a `backup.json` on phone A and copied it to phone B.
2. I chose a backup folder on phone B. That folder contains `backup.json`
3. When clicking on "Import backup" i first get an in-app message saying "Could not find the backup file".
4. After clicking on "OK" I get a toast saying "Could not read the backup file".
5. also state what is the expected result and what is the actual result.

### Technical information

- Device: A: Samsung Galaxy S10, B: Galaxy A55
- OS: A: `10`, B: `14`
- app version: A: Doesn't say in "about", but changelog says `5.7.1`. B: `7.2.0-Play`

If relevant, please say what your sync settings are, and report any odd stuff happening in general.

**Comment by CampelloManuel** [comment]
You have to rename the json file to `NoNonsenseNotes_Backup.json`, then the app will see it.
Now that I think about it, it's very counter intuitive, so I will update the description of the `Import backup` button to clarify this.

**Comment by dekiesel** [comment]
That worked, thank you very much!
